### ISSUE TITLE
No se pueden hacer modificaciones del ClientName y otros attrs al deployar los objetos

### ISSUE THREAD

**Issue by valenIndovino** [Identicum/sherpa-py-janssen#1]
Vemos que se hace el PUT pero si se modifica el clientName de un client que ya existe, este se pisa por el valor con el que se creo.
Revisar el clean_json, coinciden los attrs con los que limpia.

**Comment by ggallard** [comment]
Probar hacer el update de objetos haciendo un PATCH con el JSON que tenemos en el file.
https://gluu.org/swagger-ui/?url=https://raw.githubusercontent.com/JanssenProject/jans/v1.0.22/jans-config-api/docs/jans-config-api-swagger.yaml

**Comment by valenIndovino** [comment]
Arreglado, funcionando y deployado.
